name: "Build workflow"
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: "Get code"
        uses: actions/checkout@v4
      - name: "Install dependencies"
        run: npm i
      - name: "Lint"
        run: npm run lint
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Get code"
        uses: actions/checkout@v4
      - name: "Faking build"
        run: echo "Build done"
