name: "Build workflow"
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: "Get code"
        uses: actions/checkout@v4
      - name: "Install and cache dependencies"
        id: deps
        uses: ./.github/actions/deps
      - name: "Echo ouput action"
        run: echo "Le nom du chat est ${{ steps.deps.outputs.catname }}"
      - name: "Lint"
        run: npm run lint
  build:
    runs-on: ubuntu-latest
    needs: lint
    outputs:
      script: ${{ steps.filename.outputs.value}}
    steps:
      - name: "Get code"
        uses: actions/checkout@v4
      - name: "Install and cache dependencies"
        uses: ./.github/actions/deps
      - name: "Build"
        run: npm run build 
      - name: "User notification"
        run: echo "Build done."
      - name: Filename Output
        id: filename
        run: echo "value=zgeg" >> "$GITHUB_OUTPUT"
      - name: Upload artifcats
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: |
            /dist
            package.json
  getting_oupout:
    runs-on: ubuntu-latest
    needs: build
    env:
      OUTPUT_1: ${{ needs.build.outputs.script}}
    steps:
      - name: display output value
        run: echo "$OUTPUT_1"
      - name: Displaying context
        run: echo "${{ tojson(needs)}}"
  deployment:
    uses: "./.github/workflows/reusable.yaml"
    with: 
        os: ubuntu-latest
  testingOutput:
    runs-on: ubuntu-latest
    needs: [deployment]
    steps:
      - name: Display output
        run: echo ${{ needs.deployment.outputs.chat }}

        



      
           


        
