name: "Build workflow"
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: "Get code"
        uses: actions/checkout@v4
      - name: "Install dependencies"
        run: npm i
      - name: "Lint"
        run: npm run lint
  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: "Get code"
        uses: actions/checkout@v4
      - name: "Install dependencies"
        run: npm i
      - name: "Build"
        run: npm run build 
      - name: "User notification"
        run: echo "Build done."
      - name: Upload artifcats
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: |
            /dist
            package.json
        
